### PR TITLE
Feature/improve prepared statements

### PR DESCRIPTION
**Pull request by michalmatoga**
This is a fix to #22

### CODE REVIEW

**Comment by bryanlatten** [comment]
@michalmatoga can you rebase this on latest master?

**Comment by AndyM84** [comment]
Any chance somebody can move this forward?  Ran into an issue with prepared statements that were INSERT's and the `Pdo::lastInsertId()` method that this PR appears to resolve.  Happy to help if there's any way I can.

Thanks,

Andrew

**Comment by michalmatoga** [comment]
There you go. Sorry for such delay.

**Comment by eberfreitas** [comment]
Is there anything blocking this merge? I would gladly help if you guys need a hand.

**Comment by jimbojsb** [comment]
@eberfreitas didn't even realize that was sitting there good to go. Merged/tagged as 0.4

**Comment by eberfreitas** [comment]
Thank you :)

**Pull request merged**
